CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(1000) NOT NULL,
    create_date timestamp NOT NULL,
    creator_id BIGINT NOT NULL references users(user_id)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(500) NOT NULL,
    owner_id BIGINT NOT NULL references users(user_id),
    available BOOLEAN NOT NULL,
    request_id BIGINT references item_requests(request_id)
);

CREATE TABLE IF NOT EXISTS booking (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    tenant_id BIGINT NOT NULL references users(user_id),
    item_id BIGINT NOT NULL references items(item_id),
    status varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000) NOT NULL,
    item_id BIGINT NOT NULL references items(item_id),
    author_id BIGINT NOT NULL references users(user_id),
    created timestamp NOT NULL
);